spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create


aws:
  region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
  secrets:
    jwt-secret-name: ${AWS_JWT_SECRET_NAME}


jwt:
  expiration-time: ${JWT_EXPIRATION_TIME}
  refresh-time: ${JWT_REFRESH_TIME}


cloudfront:
  domain: ${CLOUDFRONT_DOMAIN}


api:
  prefix: /api/v1


server:
  port: 9193